# Generated by Django 2.2 on 2020-07-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.CharField(default='Write an overview to help readers the context of the aticle.', max_length=150, verbose_name='Overview'),
        ),
    ]
