# Generated by Django 2.2 on 2020-07-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(default='Write an overview to help readers the context of the aticle.', max_length=150, verbose_name='Overview'),
        ),
    ]
